### ISSUE TITLE
.button-info background-color too light in Bootstrap 5 Dark Mode

### ISSUE THREAD

**Issue by jmoppel** [DataTables/Buttons#210]
Issue:
Info pop up `background-color` is hard coded to `white` in Bootstrap 5. This is a problem for Dark Mode:

Example:
![image](https://github.com/user-attachments/assets/363481a4-ec7d-453b-8420-a6b38f76754f)

This can be corrected by overriding the background color with a Bootstrap CSS variable:
```css
div.dt-button-info {
    /* use variable instead of hard coded value */
    background-color: var(--bs-body-bg);
}
```

Corrected version:
https://live.datatables.net/kumasefa/2/edit
![image](https://github.com/user-attachments/assets/0343050d-ce6b-4b25-b793-4cae9460a447)

This CSS variable works well for both dark mode and light mode.
